name: test-workflow
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Step 1
        run: |
          echo "Running Step 1"
          sleep 30
      - run: exit 1 # force test failure

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Run Step 2
        run: |
          echo "Running Step 2"
          sleep 30

  e2e-test-1:
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npx playwright test example-1

    - name: Save and Upload Artifacts for Slack Notification
      uses: ./.github/actions/upload-artifacts
      if: ${{ !cancelled() }}
      with:
        job_name: ${{ github.job }}
        junit_path: 'test-results/junit.xml'
        report_url: 'http://www.yahoo.com' # replace with link to hosted report url

  e2e-test-2:
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npx playwright test example-2

    - name: Save and Upload Artifacts for Slack Notification
      uses: ./.github/actions/upload-artifacts
      if: ${{ !cancelled() }}
      with:
        job_name: ${{ github.job }}
        junit_path: 'test-results/junit.xml'
        report_url: 'http://www.google.com' # replace with link to hosted report url

  # slack-notify-always:
  #     if: always()
  #     needs: [job-1, job-2, e2e-test-1, e2e-test-2]
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Send Slack Notification
  #         uses: midleman/slack-workflow-status@mi/add-filter-jobs # i'm using branch instead of version # for testing purposes. should use version #
  #         with:
  #           gh_repo_token: ${{ secrets.GITHUB_TOKEN }}
  #           slack_token: ${{ secrets.SLACK_TOKEN }}
  #           slack_channel: "U07KNKY6S5C"
  #           notify_on: "always"
  #           filter_jobs: "job-1,job-2,e2e-test-1"
  #           comment_junit_failures: "true"
  #           comment_junit_flakes: "true"
  #           custom_title: "Testing my own comment title. <https://example.com|A link.>"

  # slack-notify-never:
  #   if: always()
  #   needs: [job-1, job-2, e2e-test-1, e2e-test-2]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send Slack Notification
  #       uses: midleman/slack-workflow-status@mi/add-filter-jobs # for testing changes, use branch instead of version #
  #       with:
  #         gh_repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         slack_token: ${{ secrets.SLACK_TOKEN }}
  #         slack_channel: "U07KNKY6S5C"
  #         notify_on: "never"


  slack-notify-failure:
    if: always()
    needs: [job-1, job-2, e2e-test-1, e2e-test-2]
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: midleman/slack-workflow-status@mi/add-filter-jobs # for testing changes, use branch instead of version #
        with:
          gh_repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: "U07KNKY6S5C"
          notify_on: "failure"
          filter_jobs: "e2e-test-1, e2e-test-2" # will only send notification for these jobs failing


